String = input()
vowels = sum(1 for ch in String if ch.lower() in "aeiou")
consonants = sum(1 for ch in String if ch.isalpha() and ch.lower() not in "aeiou")
digits = sum(1 for ch in String if ch.isdigit())
spaces = sum(1 for ch in String if ch == " ")
print("Vowels: ", vowels)
print("Consonants: ", consonants)
print("Digits: ", digits)
print("Spaces", spaces)